version: 2
updates:
- package-ecosystem: nuget
  groups:
    third-party-dependencies:
      patterns:
        - "*"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  reviewers:
    - jzabroski
  ignore:
    - dependency-name: FluentMigrator
      versions:
        - 5.0.0
