version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "/src"
    - "/samples"
    - "/test"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
    - jzabroski
  ignore:
    - dependency-name: FluentMigrator
      versions:
        - 5.0.0
