blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/fluentmigrator/fluentmigrator/issues/new?template=bug_report.md
    about: Report a bug using the FluentMigrator support form
  - name: Feature Request
    url: https://github.com/fluentmigrator/fluentmigrator/discussions/new?category_id=66161
    about: Share ideas for new features
  - name: Ask a Question
    url: https://github.com/fluentmigrator/fluentmigrator/discussions/new?category_id=66160
    about: Ask the community for help
